package lab8p2_equipo7;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;

/**
 *
 * @author skxka
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        as.cargarArchivo();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearUniverso = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jt_univName = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jd_crearSerVivo = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jc_universos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jt_nombreSer = new javax.swing.JTextField();
        jt_IDSer = new javax.swing.JTextField();
        js_poder = new javax.swing.JSpinner();
        js_anios = new javax.swing.JSpinner();
        jt_raza = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jb_crearSerVivo = new javax.swing.JButton();
        jd_modificarSerVivo = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jt_nombreSer1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jt_IDSer1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        js_poder1 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        js_anios1 = new javax.swing.JSpinner();
        jt_raza1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jc_serVivo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jc_universos1 = new javax.swing.JComboBox<>();
        jb_modificarSerVivo = new javax.swing.JButton();
        jd_eliminarSerVivo = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        FieldBuscarElimSerVivo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListElimSeres = new javax.swing.JList<>();
        jb_eliminarSerVivo = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        BtnModifVivo = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese el nombre del Universo");

        jButton7.setText("Crear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jt_univName)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton7)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jt_univName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jd_crearUniversoLayout = new javax.swing.GroupLayout(jd_crearUniverso.getContentPane());
        jd_crearUniverso.getContentPane().setLayout(jd_crearUniversoLayout);
        jd_crearUniversoLayout.setHorizontalGroup(
            jd_crearUniversoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_crearUniversoLayout.setVerticalGroup(
            jd_crearUniversoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(51, 0, 153));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Poder");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Años");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Universo de procedencia");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Raza");

        js_poder.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        js_anios.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Agregar ser vivo");

        jb_crearSerVivo.setText("Crear");
        jb_crearSerVivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearSerVivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_nombreSer)
                            .addComponent(jt_IDSer, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(js_poder)
                            .addComponent(js_anios))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jc_universos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jt_raza, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jb_crearSerVivo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jt_nombreSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jc_universos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_IDSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(js_poder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jt_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(js_anios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jb_crearSerVivo)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jd_crearSerVivoLayout = new javax.swing.GroupLayout(jd_crearSerVivo.getContentPane());
        jd_crearSerVivo.getContentPane().setLayout(jd_crearSerVivoLayout);
        jd_crearSerVivoLayout.setHorizontalGroup(
            jd_crearSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_crearSerVivoLayout.setVerticalGroup(
            jd_crearSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(51, 0, 153));

        jLabel9.setText("Nombre");

        jLabel10.setText("ID");

        jLabel11.setText("Poder");

        js_poder1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel12.setText("Años");

        js_anios1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel13.setText("Raza");

        jLabel14.setText("Universo de procedencia");

        jc_serVivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jc_serVivoItemStateChanged(evt);
            }
        });

        jLabel15.setText("Elegir ser vivo");

        jc_universos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jb_modificarSerVivo.setText("Modificar");
        jb_modificarSerVivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarSerVivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jc_universos1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel15)
                        .addGap(38, 38, 38)
                        .addComponent(jc_serVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jb_modificarSerVivo)))
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12))
                    .addGap(34, 34, 34)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jt_nombreSer1)
                        .addComponent(jt_IDSer1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addComponent(js_poder1)
                        .addComponent(js_anios1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addComponent(jt_raza1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_serVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(71, 71, 71)
                .addComponent(jc_universos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(jb_modificarSerVivo)
                .addGap(26, 26, 26))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel14)
                        .addComponent(jt_nombreSer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jt_IDSer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(42, 42, 42)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel13)
                        .addComponent(js_poder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jt_raza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(js_anios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(82, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jd_modificarSerVivoLayout = new javax.swing.GroupLayout(jd_modificarSerVivo.getContentPane());
        jd_modificarSerVivo.getContentPane().setLayout(jd_modificarSerVivoLayout);
        jd_modificarSerVivoLayout.setHorizontalGroup(
            jd_modificarSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_modificarSerVivoLayout.setVerticalGroup(
            jd_modificarSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(51, 0, 153));

        FieldBuscarElimSerVivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldBuscarElimSerVivoKeyReleased(evt);
            }
        });

        JListElimSeres.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(JListElimSeres);

        jb_eliminarSerVivo.setText("Eliminar");
        jb_eliminarSerVivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarSerVivoActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Escriba el nombre de un ser vivo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(FieldBuscarElimSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(64, 64, 64))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jb_eliminarSerVivo)
                            .addGap(153, 153, 153)))
                    .addComponent(jLabel16)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(FieldBuscarElimSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_eliminarSerVivo)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jd_eliminarSerVivoLayout = new javax.swing.GroupLayout(jd_eliminarSerVivo.getContentPane());
        jd_eliminarSerVivo.getContentPane().setLayout(jd_eliminarSerVivoLayout);
        jd_eliminarSerVivoLayout.setHorizontalGroup(
            jd_eliminarSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_eliminarSerVivoLayout.setVerticalGroup(
            jd_eliminarSerVivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jButton1.setText("Crear Universo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar Universo");

        jButton3.setText("Eliminar Universo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(jButton2))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButton1)
                .addGap(42, 42, 42)
                .addComponent(jButton2)
                .addGap(47, 47, 47)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 0, 153));

        jButton4.setText("Crear Ser Vivo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        BtnModifVivo.setText("Modificar Ser Vivo");
        BtnModifVivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifVivoActionPerformed(evt);
            }
        });

        jButton6.setText("Eliminar Ser VIvo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(jButton4))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(BtnModifVivo))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButton4)
                .addGap(42, 42, 42)
                .addComponent(BtnModifVivo)
                .addGap(53, 53, 53)
                .addComponent(jButton6)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jd_crearUniverso.setModal(true);
        jd_crearUniverso.pack();
        jd_crearUniverso.setLocationRelativeTo(this);
        jd_crearUniverso.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (jt_univName.getText() != "") {
            Universo u = new Universo(jt_univName.getText());
            universos.add(u);
            JOptionPane.showMessageDialog(jd_crearUniverso, "Universo creado exitosamente");
            jd_crearUniverso.dispose();
            jt_univName.setText("");
            int cantSeres = u.getCitizens().size();
            
            adminUniversos au = new adminUniversos("./Universo.uni");
            au.cargarArchivo();
            au.setListaUniversos(universos);
            au.escribirArchivo();
            
            //agregar
       Dba db = new Dba("./Universos.accdb");
        db.conectar();
        try {
            
            db.query.execute("INSERT INTO Universos"
                    + " (CantidadSeres,Universo)"
                    + " VALUES ('" + cantSeres+ "', '" + u.getNombre()+ "')");
            db.commit();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (universos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existen universos para añadir seres vivos");
        } else {
            refreshComboBoxUniverso();
            jd_crearSerVivo.setModal(true);
            jd_crearSerVivo.pack();
            jd_crearSerVivo.setLocationRelativeTo(this);
            jd_crearSerVivo.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jb_crearSerVivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearSerVivoActionPerformed
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jc_universos.getModel();
        Universo u = (Universo) modelo.getSelectedItem();
        Universo uni = (Universo) jc_universos.getSelectedItem();

        SeresVivos sv = new SeresVivos(jt_nombreSer.getText(), jt_IDSer.getText(), jt_raza.getText(),
                (Integer) js_poder.getValue(), (Integer) js_anios.getValue(), uni);
        as.getListaSeres().add(sv);
        u.getCitizens().add(sv);
        JOptionPane.showMessageDialog(jd_crearUniverso, "Universo creado exitosamente");
        jd_crearUniverso.dispose();

//        as.setListaSeres(as.getListaSeres());
        //as.setSer(sv);
        as.escribirArchivo();

        jt_nombreSer.setText("");
        jt_IDSer.setText("");
        jt_raza.setText("");
        js_poder.setValue(1);
        js_anios.setValue(1);

    }//GEN-LAST:event_jb_crearSerVivoActionPerformed

    private void BtnModifVivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifVivoActionPerformed
        refreshComboBoxSerVivo(as);
        refreshComboBoxUniverso1();
//        SeresVivos primerSer = (SeresVivos) jc_serVivo.getSelectedItem();
//        jc_universos1.setSelectedItem(primerSer.getUniverso());

        jd_modificarSerVivo.setModal(true);
        jd_modificarSerVivo.pack();
        jd_modificarSerVivo.setLocationRelativeTo(this);
        jd_modificarSerVivo.setVisible(true);
    }//GEN-LAST:event_BtnModifVivoActionPerformed

    private void jc_serVivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jc_serVivoItemStateChanged

        if (jc_serVivo.getSelectedIndex() >= 0) {
            SeresVivos sv = (SeresVivos) jc_serVivo.getSelectedItem();
            jt_nombreSer1.setText(sv.getNombre());
            jt_IDSer1.setText(sv.getID());
            jt_raza1.setText(sv.getRaza());
            js_poder1.setValue(sv.getPoder());
            js_anios1.setValue(sv.getAnios());
            jc_universos1.setSelectedItem(sv.getUniverso());
        }
    }//GEN-LAST:event_jc_serVivoItemStateChanged

    private void jb_modificarSerVivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarSerVivoActionPerformed
        SeresVivos sv = (SeresVivos) jc_serVivo.getSelectedItem();

        sv.setNombre(jt_nombreSer1.getText());
        sv.setID(jt_IDSer1.getText());
        sv.setAnios((Integer) js_anios.getValue());
        sv.setPoder((Integer) js_poder1.getValue());
        sv.setUniverso((Universo) jc_universos1.getSelectedItem());
        sv.setRaza(jt_raza1.getText());

        JOptionPane.showMessageDialog(this, "Ser vivo modificado exitosamente");
//        as.setListaSeres(seresVivos);
//as.setSer(sv);
        as.escribirArchivo();
    }//GEN-LAST:event_jb_modificarSerVivoActionPerformed

    private void FieldBuscarElimSerVivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldBuscarElimSerVivoKeyReleased

        DefaultListModel modelo = new DefaultListModel();
        for (SeresVivos s : as.getListaSeres()) {
            if (s.getNombre().startsWith(FieldBuscarElimSerVivo.getText())) {
                modelo.addElement(s);
            }
        }
        JListElimSeres.setModel(modelo);
    }//GEN-LAST:event_FieldBuscarElimSerVivoKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jd_eliminarSerVivo.setModal(true);
        jd_eliminarSerVivo.pack();
        jd_eliminarSerVivo.setLocationRelativeTo(this);
        jd_eliminarSerVivo.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jb_eliminarSerVivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarSerVivoActionPerformed
        if(JListElimSeres.getSelectedIndex()>= 0){
            DefaultListModel modelo = new DefaultListModel();
            as.getListaSeres().remove((SeresVivos)modelo.getElementAt(JListElimSeres.getSelectedIndex()));
            as.escribirArchivo();
        }
    }//GEN-LAST:event_jb_eliminarSerVivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void refreshComboBoxUniverso() {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jc_universos.getModel();
        modelo.removeAllElements();
        for (Universo u : universos) {
            modelo.addElement(u);
        }
        jc_universos.setModel(modelo);
    }

    public void refreshComboBoxSerVivo(adminSeres a) {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jc_serVivo.getModel();
        modelo.removeAllElements();
        for (SeresVivos sv : a.getListaSeres()) {
            modelo.addElement(sv);
        }
        jc_serVivo.setModel(modelo);
    }

    public void refreshComboBoxUniverso1() {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jc_universos1.getModel();
        modelo.removeAllElements();
        for (Universo u : universos) {
            modelo.addElement(u);
        }
        jc_universos1.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnModifVivo;
    private javax.swing.JTextField FieldBuscarElimSerVivo;
    private javax.swing.JList<String> JListElimSeres;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_crearSerVivo;
    private javax.swing.JButton jb_eliminarSerVivo;
    private javax.swing.JButton jb_modificarSerVivo;
    private javax.swing.JComboBox<String> jc_serVivo;
    private javax.swing.JComboBox<String> jc_universos;
    private javax.swing.JComboBox<String> jc_universos1;
    private javax.swing.JDialog jd_crearSerVivo;
    private javax.swing.JDialog jd_crearUniverso;
    private javax.swing.JDialog jd_eliminarSerVivo;
    private javax.swing.JDialog jd_modificarSerVivo;
    private javax.swing.JSpinner js_anios;
    private javax.swing.JSpinner js_anios1;
    private javax.swing.JSpinner js_poder;
    private javax.swing.JSpinner js_poder1;
    private javax.swing.JTextField jt_IDSer;
    private javax.swing.JTextField jt_IDSer1;
    private javax.swing.JTextField jt_nombreSer;
    private javax.swing.JTextField jt_nombreSer1;
    private javax.swing.JTextField jt_raza;
    private javax.swing.JTextField jt_raza1;
    private javax.swing.JTextField jt_univName;
    // End of variables declaration//GEN-END:variables

    public ArrayList<Universo> universos = new ArrayList();

    public adminSeres as = new adminSeres("./seres.sre");

}
